[package]
name = "reveldb"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "*"
bytes = { version = "*", features = ["serde"] }
clap = { version = "*", features = ["derive"] }
leveldb = "*"
